version: '3'

services:
  flask-chatbot.pri:
    build:
      context: .
      dockerfile: dockerfile
    ports:
        - "5000:5000"
    environment:
      line_channel_access_token: 'Your line chatbot access token'
      line_channel_secret: 'Your line channel secret'
      line_db_host: 'mongo.pri'
    volumes:
        - .:/app

  ngrok-temp:
    image: wernight/ngrok
    ports:
      - "4040:4040"
    command: ngrok http flask-chatbot.pri:5000 -region ap
    depends_on:
      - flask-chatbot.pri

  mongo.pri:
    image: mongo:3.6.12
    container_name: mongo.pri
    restart: always

  mongo-express.pri:
    image: mongo-express:0.54.0
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo.pri
#      ME_CONFIG_MONGODB_ADMINUSERNAME: root
#      ME_CONFIG_MONGODB_ADMINPASSWORD: example